name: CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        cc: [ clang, gcc ]
        make: [ bmake, pmake ]
        exclude:
          - os: macos-latest
            make: pmake
          - os: macos-latest
            cc: gcc # it's clang anyway
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        uname -a
        sudo apt-get install pmake bmake
        ${{ matrix.cc }} --version

    - name: dependencies (MacOS)
      if: matrix.os == 'macos-latest'
      run: |
        uname -a
        brew install bmake
        ${{ matrix.cc }} --version

    - name: make
      run: ${{ matrix.make }} -r -j 2 PKGCONF=pkg-config CC=${{ matrix.cc }}

    - name: install
      run: ${{ matrix.make }} -r -j 2 PKGCONF=pkg-config PREFIX=/tmp/p install

    - uses: actions/upload-artifact@v2
      with:
        name: kgt-${{ github.sha }}
        path: /tmp/p/

