name: Emscripten

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        cc: [ emcc ]
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: dependencies
      run: |
        sudo apt-get update
        sudo apt-get install bmake emscripten
        emcc -v # first run to generate ~/.emscripten
        emcc -v # informational

    - name: make
      run: bmake -r -j 2 DEBUG=1 PKGCONF=pkg-config CC=${{ matrix.cc }}

