name: Emscripten

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        cc: [ emcc ]
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    # the xenial emscripten package is old (and doesn't support wasm);
    # this brings in emsdk which is more recent, and does.
    - uses: mymindstorm/setup-emsdk@v7

    - name: dependencies
      run: |
        sudo apt-get update
        sudo apt-get install bmake
        # emcc -v # first run to generate ~/.emscripten only needed for system package
        emcc -v # informational

    - name: make
      run: bmake -r -j 2 DEBUG=1 PKGCONF=pkg-config CC=${{ matrix.cc }}

