name: Sanitizers

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        san: [ ASAN, UBSAN, MSAN, EFENCE ]
        os: [ ubuntu-latest, macos-latest ]
        cc: [ clang, gcc ]
        exclude:
          - os: macos-latest
            cc: gcc # it's clang anyway
          - os: macos-latest
            san: EFENCE # not packaged
          - os: macos-latest
            san: MSAN # not supported
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        uname -a
        sudo apt-get install bmake electric-fence
        ${{ matrix.cc }} --version

    - name: dependencies (MacOS)
      if: matrix.os == 'macos-latest'
      run: |
        uname -a
        brew install bmake
        ${{ matrix.cc }} --version

    - name: make
      run: bmake -r -j 2 ${{ matrix.san }}=1 DEBUG=1 PKGCONF=pkg-config CC=${{ matrix.cc }}

    - name: test
      # I don't want to build SID just for sake of its -l test
      # Same for lx
      run: bmake -r -j 2 ${{ matrix.san }}=1 DEBUG=1 PKGCONF=pkg-config SID='true; echo sid' LX='true; echo lx' CC=${{ matrix.cc }} test

